//! Float signal-processing primitives shared by the SILK encoder's analysis front end
//! (libopus `silk/float/SigProc_FLP.h` plus the one-kernel-per-file `silk/float/*_FLP.c` set).
//!
//! # Why these are float and the decoder is not
//!
//! RFC 6716 §4.2 is normative for the **decoder** only; the encoder is free to make any decision it
//! likes as long as the result decodes. libopus ships two encoder builds — `silk/fixed/` and
//! `silk/float/` — and the two do *not* produce the same bitstream. This port follows the float
//! build, matching the CELT side ([`crate::opus::celt`]), so these kernels are `f32` (`silk_float`)
//! with `f64` accumulators exactly where the C uses `double`. The accumulator width is not a detail:
//! [`energy`] and [`inner_product`] accumulate in `double` over hundreds of terms and a `f32`
//! accumulator visibly changes the pitch search's winner.
//!
//! # What "matches the C" means here
//!
//! Every kernel below reproduces the C's *operation order*, including its 4× unrolled sums, because
//! floating-point addition is not associative. What it cannot promise is the last ulp: GCC compiles
//! libopus with `-ffp-contract=fast` by default, so a C `a * b + c` may become a single fused
//! multiply-add while Rust never contracts. Differences are therefore at the 1e-7 relative level on
//! `f32` outputs and 1e-15 on `f64` ones. Everything downstream that produces a *discrete* result —
//! a codebook index, a pitch lag, a survivor — is required to match exactly; see the conformance
//! harness for the per-kernel tolerances.

use core::f32::consts::PI;

/// Which half of a sine window [`apply_sine_window`] applies (`apply_sine_window_FLP.c:34-37`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SineWindow {
    /// `win_type == 1` — rising, sine from 0 to pi/2.
    Rising,
    /// `win_type == 2` — falling, sine from pi/2 to pi.
    Falling,
}

/// `silk_energy_FLP(data, dataSize)` (`energy_FLP.c:35-59`) — sum of squares, accumulated in
/// `double`.
///
/// The 4× unrolled shape is the C's and is reproduced rather than simplified: the four products are
/// summed left-to-right into one term first, and only that term is added to the running total, so a
/// plain `iter().map(..).sum()` would round differently.
#[must_use]
pub fn energy(data: &[f32]) -> f64 {
    let mut result = 0.0f64;
    let mut index = 0usize;
    while index + 4 <= data.len() {
        let a = f64::from(data[index]) * f64::from(data[index]);
        let b = f64::from(data[index + 1]) * f64::from(data[index + 1]);
        let c = f64::from(data[index + 2]) * f64::from(data[index + 2]);
        let d = f64::from(data[index + 3]) * f64::from(data[index + 3]);
        result += a + b + c + d;
        index += 4;
    }
    while index < data.len() {
        result += f64::from(data[index]) * f64::from(data[index]);
        index += 1;
    }
    result
}

/// `silk_inner_product_FLP(data1, data2, dataSize)` (`inner_product_FLP.c:35-59`) — dot product
/// accumulated in `double`, with the same 4× unrolled summation order as [`energy`].
///
/// The length is the shorter of the two slices, which is how every call site uses it.
#[must_use]
pub fn inner_product(data1: &[f32], data2: &[f32]) -> f64 {
    let length = data1.len().min(data2.len());
    let mut result = 0.0f64;
    let mut index = 0usize;
    while index + 4 <= length {
        let a = f64::from(data1[index]) * f64::from(data2[index]);
        let b = f64::from(data1[index + 1]) * f64::from(data2[index + 1]);
        let c = f64::from(data1[index + 2]) * f64::from(data2[index + 2]);
        let d = f64::from(data1[index + 3]) * f64::from(data2[index + 3]);
        result += a + b + c + d;
        index += 4;
    }
    while index < length {
        result += f64::from(data1[index]) * f64::from(data2[index]);
        index += 1;
    }
    result
}

/// `silk_apply_sine_window_FLP(px_win, px, win_type, length)` (`apply_sine_window_FLP.c:38-81`).
///
/// The window is generated by the recurrence `sin(n*f) = 2*cos(f)*sin((n-1)*f) - sin((n-2)*f)` with
/// `2*cos(f)` **approximated** as `2 - f*f`, not computed. That approximation is part of the
/// reference — using a real cosine here changes the autocorrelation and, through it, the LPC
/// analysis — so it is reproduced verbatim.
///
/// `output` and `input` must be the same length, and that length must be a multiple of 4 (the C
/// asserts it; every call site satisfies it because the window lengths are multiples of the sample
/// rate in kHz).
pub fn apply_sine_window(output: &mut [f32], input: &[f32], window_type: SineWindow) {
    let length = output.len().min(input.len());
    debug_assert_eq!(
        length % 4,
        0,
        "silk enc: sine window length must be 4-aligned"
    );
    if length == 0 {
        return;
    }

    let frequency = PI / (length as f32 + 1.0);
    // Approximation of 2 * cos(f).
    let two_cos = 2.0f32 - frequency * frequency;

    let (mut state0, mut state1) = match window_type {
        // Start from 0; approximation of sin(f).
        SineWindow::Rising => (0.0f32, frequency),
        // Start from 1; approximation of cos(f).
        SineWindow::Falling => (1.0f32, 0.5f32 * two_cos),
    };

    let mut index = 0usize;
    while index + 4 <= length {
        output[index] = input[index] * 0.5f32 * (state0 + state1);
        output[index + 1] = input[index + 1] * state1;
        state0 = two_cos * state1 - state0;
        output[index + 2] = input[index + 2] * 0.5f32 * (state1 + state0);
        output[index + 3] = input[index + 3] * state0;
        state1 = two_cos * state0 - state1;
        index += 4;
    }
}

/// `silk_autocorrelation_FLP(results, inputData, inputDataSize, correlationCount)`
/// (`autocorrelation_FLP.c:36-53`) — the first `results.len()` autocorrelation taps of `input`.
///
/// As in the C, the tap count is clamped to the input length.
pub fn autocorrelation(results: &mut [f32], input: &[f32]) {
    let count = results.len().min(input.len());
    for (lag, slot) in results.iter_mut().enumerate().take(count) {
        *slot = inner_product(input, &input[lag..]) as f32;
    }
}

/// `silk_warped_autocorrelation_FLP(corr, input, warping, length, order)`
/// (`warped_autocorrelation_FLP.c:35-75`) — autocorrelation on a warped (bilinear) frequency axis,
/// used by the noise-shaping analysis at complexity levels that enable warping.
///
/// `corr` must hold `order + 1` entries and `order` must be even (the C asserts it). The state runs
/// in `double`; the C's comment explains the deliberately un-factored `state[i] + w*state[i+1] -
/// w*tmp1` form (two multiplies, shorter dependency chain), and that form is kept because factoring
/// it changes the rounding.
pub fn warped_autocorrelation(corr: &mut [f32], input: &[f32], warping: f32, order: usize) {
    debug_assert_eq!(
        order % 2,
        0,
        "silk enc: warped autocorrelation order must be even"
    );
    debug_assert!(corr.len() > order);
    /// `MAX_SHAPE_LPC_ORDER + 1` (`define.h:155`).
    const STATE_LEN: usize = super::MAX_SHAPE_LPC_ORDER + 1;
    let mut state = [0.0f64; STATE_LEN];
    let mut accumulator = [0.0f64; STATE_LEN];
    let warping = f64::from(warping);

    for &sample in input {
        let mut tmp1 = f64::from(sample);
        let mut index = 0usize;
        while index < order {
            let tmp2 = state[index] + warping * state[index + 1] - warping * tmp1;
            state[index] = tmp1;
            accumulator[index] += state[0] * tmp1;
            tmp1 = state[index + 1] + warping * state[index + 2] - warping * tmp2;
            state[index + 1] = tmp2;
            accumulator[index + 1] += state[0] * tmp2;
            index += 2;
        }
        state[order] = tmp1;
        accumulator[order] += state[0] * tmp1;
    }

    for (slot, &value) in corr.iter_mut().zip(accumulator.iter()).take(order + 1) {
        *slot = value as f32;
    }
}

/// `silk_schur_FLP(refl_coef, auto_corr, order)` (`schur_FLP.c:34-70`) — the Schur recursion,
/// returning the residual energy and writing `order` reflection coefficients.
///
/// `auto_corr` must hold `order + 1` entries. The `1e-9` floor on the denominator is the C's and is
/// what makes an all-zero input return 0 rather than a NaN.
#[must_use]
pub fn schur(refl_coef: &mut [f32], auto_corr: &[f32]) -> f32 {
    let order = refl_coef.len();
    debug_assert!(auto_corr.len() > order);
    /// The largest `order` any caller uses: the noise-shaping analysis' `MAX_SHAPE_LPC_ORDER`
    /// (24) beats the pitch analysis' `MAX_FIND_PITCH_LPC_ORDER` (16), so this bound covers both.
    const MAX_ORDER: usize = super::MAX_SHAPE_LPC_ORDER + 1;
    let mut lower = [0.0f64; MAX_ORDER];
    let mut upper = [0.0f64; MAX_ORDER];

    for index in 0..=order {
        lower[index] = f64::from(auto_corr[index]);
        upper[index] = f64::from(auto_corr[index]);
    }

    for k in 0..order {
        // silk_max_float( C[0][1], 1e-9f ) — the C compares against the float literal.
        let denominator = if upper[0] > f64::from(1e-9f32) {
            upper[0]
        } else {
            f64::from(1e-9f32)
        };
        let reflection = -lower[k + 1] / denominator;
        refl_coef[k] = reflection as f32;

        for n in 0..(order - k) {
            let c1 = lower[n + k + 1];
            let c2 = upper[n];
            lower[n + k + 1] = c1 + c2 * reflection;
            upper[n] = c2 + c1 * reflection;
        }
    }

    upper[0] as f32
}

/// `silk_k2a_FLP(A, rc, order)` (`k2a_FLP.c:35-54`) — step-up recursion turning reflection
/// coefficients into prediction coefficients, in place over `A[..order]`.
pub fn k2a(coefficients: &mut [f32], reflection: &[f32]) {
    let order = reflection.len().min(coefficients.len());
    for k in 0..order {
        let rck = reflection[k];
        for n in 0..((k + 1) >> 1) {
            let tmp1 = coefficients[n];
            let tmp2 = coefficients[k - n - 1];
            coefficients[n] = tmp1 + tmp2 * rck;
            coefficients[k - n - 1] = tmp2 + tmp1 * rck;
        }
        coefficients[k] = -rck;
    }
}

/// `silk_bwexpander_FLP(ar, d, chirp)` (`bwexpander_FLP.c:35-49`) — multiply coefficient `k` by
/// `chirp^(k+1)`, in place.
///
/// Note the last coefficient uses the *already advanced* factor, i.e. the loop runs `d - 1` times
/// and the tail applies `cfac` once more; that off-by-one is the C's and is load-bearing.
pub fn bwexpander(coefficients: &mut [f32], chirp: f32) {
    let order = coefficients.len();
    if order == 0 {
        return;
    }
    let mut factor = chirp;
    for coefficient in coefficients.iter_mut().take(order - 1) {
        *coefficient *= factor;
        factor *= chirp;
    }
    coefficients[order - 1] *= factor;
}

/// `silk_LPC_analysis_filter_FLP(r_LPC, PredCoef, s, length, Order)`
/// (`LPC_analysis_filter_FLP.c:210-248`) — the whitening filter `r[n] = s[n] - sum_j a[j]*s[n-1-j]`.
///
/// The first `order` outputs are zeroed, exactly as the C does after the filter loop: the filter
/// always starts from zero state, so those samples have no defined value. The C carries five
/// hand-unrolled orders (6/8/10/12/16); they are one loop here, summed in the same ascending-`j`
/// order so the rounding matches.
pub fn lpc_analysis_filter(residual: &mut [f32], pred_coef: &[f32], signal: &[f32], length: usize) {
    let order = pred_coef.len();
    debug_assert!(
        order <= length,
        "silk enc: LPC order must not exceed the block length"
    );
    let length = length.min(residual.len()).min(signal.len());
    for index in order..length {
        let mut prediction = 0.0f32;
        for (tap, &coefficient) in pred_coef.iter().enumerate() {
            prediction += signal[index - 1 - tap] * coefficient;
        }
        residual[index] = signal[index] - prediction;
    }
    for slot in residual.iter_mut().take(order.min(length)) {
        *slot = 0.0;
    }
}

/// `silk_scale_copy_vector_FLP(data_out, data_in, gain, dataSize)` (`scale_copy_vector_FLP.c`).
pub fn scale_copy_vector(output: &mut [f32], input: &[f32], gain: f32) {
    for (slot, &value) in output.iter_mut().zip(input.iter()) {
        *slot = gain * value;
    }
}

/// `silk_scale_vector_FLP(data1, gain, dataSize)` (`scale_vector_FLP.c`).
pub fn scale_vector(data: &mut [f32], gain: f32) {
    for value in data.iter_mut() {
        *value *= gain;
    }
}

/// `silk_insertion_sort_decreasing_FLP(a, idx, L, K)` (`sort_FLP.c:39-83`) — partial sort that
/// guarantees only the first `k` positions, which is all the pitch search's candidate list needs.
///
/// `indices` receives the original position of each of those `k` values. The tail pass (`i >= k`)
/// deliberately does **not** maintain positions past `k - 1`, so `values[k..]` is left in an
/// arbitrary order; callers must not read it, and the pitch search does not.
pub fn insertion_sort_decreasing(values: &mut [f32], indices: &mut [usize], k: usize) {
    let length = values.len();
    debug_assert!(k > 0 && k <= length && k <= indices.len());
    if k == 0 || length == 0 {
        return;
    }

    for (position, slot) in indices.iter_mut().enumerate().take(k) {
        *slot = position;
    }

    for i in 1..k {
        let value = values[i];
        let mut j = i;
        while j > 0 && value > values[j - 1] {
            values[j] = values[j - 1];
            indices[j] = indices[j - 1];
            j -= 1;
        }
        values[j] = value;
        indices[j] = i;
    }

    for i in k..length {
        let value = values[i];
        if value > values[k - 1] {
            let mut j = k - 1;
            while j > 0 && value > values[j - 1] {
                values[j] = values[j - 1];
                indices[j] = indices[j - 1];
                j -= 1;
            }
            values[j] = value;
            indices[j] = i;
        }
    }
}

/// `silk_insertion_sort_increasing(a, idx, L, K)` (`sort.c:41-88`) — the `opus_int32` increasing
/// twin of [`insertion_sort_decreasing`], used to pick the NLSF first-stage survivors and then the
/// best rate-distortion path among them.
pub fn insertion_sort_increasing_i32(values: &mut [i32], indices: &mut [usize], k: usize) {
    let length = values.len();
    debug_assert!(k > 0 && k <= length && k <= indices.len());
    if k == 0 || length == 0 {
        return;
    }

    for (position, slot) in indices.iter_mut().enumerate().take(k) {
        *slot = position;
    }

    for i in 1..k {
        let value = values[i];
        let mut j = i;
        while j > 0 && value < values[j - 1] {
            values[j] = values[j - 1];
            indices[j] = indices[j - 1];
            j -= 1;
        }
        values[j] = value;
        indices[j] = i;
    }

    for i in k..length {
        let value = values[i];
        if value < values[k - 1] {
            let mut j = k - 1;
            while j > 0 && value < values[j - 1] {
                values[j] = values[j - 1];
                indices[j] = indices[j - 1];
                j -= 1;
            }
            values[j] = value;
            indices[j] = i;
        }
    }
}

/// libopus' own truncated `log2(10)` (`SigProc_FLP.h:198`).
///
/// Deliberately **not** [`core::f64::consts::LOG2_10`]: the C spells the constant with 15 significant
/// digits, which is a different `f64` than the correctly rounded one (…8873600 vs …8873623). The
/// pitch search compares biased correlations derived from this, so the two-ulp difference is kept
/// rather than "corrected".
#[allow(clippy::approx_constant)]
const LOG2_OF_10: f64 = 3.321_928_094_887_36;

/// `silk_log2(x)` (`SigProc_FLP.h:196-199`) — `log2(x)` computed as `3.32192809488736 * log10(x)`.
///
/// The C's comment says the `log10` route "helps the fixed-point conversion"; it is *not* the same
/// as `log2` to the last bit, and the pitch search's short-lag bias compares against it, so the
/// spelling is preserved.
#[must_use]
pub fn log2(x: f64) -> f32 {
    (LOG2_OF_10 * x.log10()) as f32
}

/// `silk_sigmoid(x)` (`SigProc_FLP.h:158-161`) — `1 / (1 + exp(-x))`, evaluated in `double`.
#[must_use]
pub fn sigmoid(x: f32) -> f32 {
    (1.0f64 / (1.0f64 + (-f64::from(x)).exp())) as f32
}

/// `silk_float2int(x)` (`SigProc_FLP.h:164-167`, i.e. `lrintf`) — round to nearest, **ties to
/// even**, which is the default IEEE rounding mode `lrintf` inherits.
///
/// Ties-to-even rather than away-from-zero matters: `silk_A2NLSF_FLP` feeds this every LPC
/// coefficient scaled by 65536, and a half-ulp disagreement changes a Q16 coefficient, which can
/// change an NLSF root, which changes a codebook index.
#[must_use]
pub fn float2int(x: f32) -> i32 {
    x.round_ties_even() as i32
}

/// `silk_float2short_array(out, in, length)` (`SigProc_FLP.h:170-180`) — [`float2int`] then
/// `silk_SAT16`.
pub fn float2short_array(output: &mut [i16], input: &[f32]) {
    for (slot, &value) in output.iter_mut().zip(input.iter()) {
        *slot = float2int(value).clamp(i32::from(i16::MIN), i32::from(i16::MAX)) as i16;
    }
}

/// `silk_short2float_array(out, in, length)` (`SigProc_FLP.h:183-193`).
pub fn short2float_array(output: &mut [f32], input: &[i16]) {
    for (slot, &value) in output.iter_mut().zip(input.iter()) {
        *slot = f32::from(value);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn energy_is_the_sum_of_squares() {
        assert_eq!(energy(&[]), 0.0);
        assert_eq!(energy(&[3.0]), 9.0);
        assert_eq!(energy(&[1.0, 2.0, 3.0, 4.0]), 30.0);
        // Seven elements exercises both the unrolled body and the tail.
        assert_eq!(energy(&[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]), 7.0);
        assert_eq!(energy(&[-2.0, -2.0]), 8.0);
    }

    #[test]
    fn inner_product_matches_a_naive_dot() {
        assert_eq!(inner_product(&[1.0, 2.0, 3.0], &[4.0, 5.0, 6.0]), 32.0);
        // Shorter slice wins.
        assert_eq!(inner_product(&[1.0, 2.0, 3.0], &[4.0]), 4.0);
        assert_eq!(inner_product(&[], &[1.0]), 0.0);
        // The autocorrelation-at-lag-0 identity.
        let signal = [0.5f32, -1.25, 3.0, 2.0, -0.75, 4.0];
        assert_eq!(inner_product(&signal, &signal), energy(&signal));
    }

    /// The window is the C's *approximation*, so pin it against an independently computed
    /// recurrence rather than against `sin()`. The endpoints are what matter: a rising window
    /// starts near 0, a falling one starts at 1.
    #[test]
    fn sine_window_endpoints_and_monotonicity() {
        let input = [1.0f32; 32];
        let mut rising = [0.0f32; 32];
        apply_sine_window(&mut rising, &input, SineWindow::Rising);
        assert!(rising[0] > 0.0 && rising[0] < 0.1, "starts near zero");
        assert!(rising[31] > 0.99, "ends near one: {}", rising[31]);
        for pair in rising.windows(2) {
            assert!(pair[1] >= pair[0], "rising window must not decrease");
        }

        let mut falling = [0.0f32; 32];
        apply_sine_window(&mut falling, &input, SineWindow::Falling);
        assert!(falling[0] > 0.99, "starts near one: {}", falling[0]);
        assert!(falling[31] < 0.1, "ends near zero: {}", falling[31]);
        for pair in falling.windows(2) {
            assert!(pair[1] <= pair[0], "falling window must not increase");
        }
    }

    /// A rising and a falling window of the same length are time reverses of each other to within
    /// the recurrence's own error — a strong structural check on the approximation constants.
    #[test]
    fn sine_windows_are_mirror_images() {
        let input = [1.0f32; 64];
        let mut rising = [0.0f32; 64];
        let mut falling = [0.0f32; 64];
        apply_sine_window(&mut rising, &input, SineWindow::Rising);
        apply_sine_window(&mut falling, &input, SineWindow::Falling);
        for index in 0..64 {
            let mirrored = falling[63 - index];
            assert!(
                (rising[index] - mirrored).abs() < 0.02,
                "tap {index}: {} vs {mirrored}",
                rising[index]
            );
        }
    }

    #[test]
    fn autocorrelation_of_a_constant_is_a_ramp_down() {
        let input = [1.0f32; 8];
        let mut result = [0.0f32; 4];
        autocorrelation(&mut result, &input);
        assert_eq!(result, [8.0, 7.0, 6.0, 5.0]);
    }

    /// Warping of zero must reduce to the plain autocorrelation — the identity the noise-shaping
    /// analysis relies on when `warping_Q16 == 0`.
    #[test]
    fn warped_autocorrelation_with_zero_warping_is_plain_autocorrelation() {
        let input: Vec<f32> = (0..40).map(|n| ((n * 7) % 13) as f32 - 6.0).collect();
        let mut warped = [0.0f32; 9];
        warped_autocorrelation(&mut warped, &input, 0.0, 8);
        let mut plain = [0.0f32; 9];
        autocorrelation(&mut plain, &input);
        for lag in 0..9 {
            let tolerance = plain[lag].abs() * 1e-5 + 1e-3;
            assert!(
                (warped[lag] - plain[lag]).abs() <= tolerance,
                "lag {lag}: {} vs {}",
                warped[lag],
                plain[lag]
            );
        }
    }

    /// Schur on a white autocorrelation (only lag 0 non-zero) gives all-zero reflection
    /// coefficients and returns the input energy unchanged.
    #[test]
    fn schur_of_white_input_is_flat() {
        let auto_corr = [10.0f32, 0.0, 0.0, 0.0, 0.0];
        let mut reflection = [1.0f32; 4];
        let residual = schur(&mut reflection, &auto_corr);
        assert_eq!(reflection, [0.0; 4]);
        assert_eq!(residual, 10.0);
    }

    /// A single-pole AR(1) process with correlation `rho` must give `rc[0] = -rho` and residual
    /// energy `R0 * (1 - rho^2)` — the textbook first Schur step, checked against closed form.
    #[test]
    fn schur_recovers_a_first_order_reflection_coefficient() {
        let rho = 0.8f32;
        let auto_corr = [1.0f32, rho, rho * rho, rho * rho * rho];
        let mut reflection = [0.0f32; 3];
        let residual = schur(&mut reflection, &auto_corr);
        assert!((reflection[0] + rho).abs() < 1e-6, "{}", reflection[0]);
        assert!(reflection[1].abs() < 1e-6, "{}", reflection[1]);
        assert!(reflection[2].abs() < 1e-6, "{}", reflection[2]);
        assert!((residual - (1.0 - rho * rho)).abs() < 1e-6, "{residual}");
    }

    /// `k2a` on a single reflection coefficient is just its negation; on two it is the standard
    /// Levinson step. Both are checked in closed form.
    #[test]
    fn k2a_matches_the_levinson_step_up() {
        let mut coefficients = [0.0f32; 1];
        k2a(&mut coefficients, &[0.5]);
        assert_eq!(coefficients, [-0.5]);

        let mut coefficients = [0.0f32; 2];
        k2a(&mut coefficients, &[0.5, 0.25]);
        // a1 = -rc0 + rc1 * (-rc0)... expanded: A[0] = -0.5 + 0.25 * -0.5 = -0.625, A[1] = -0.25.
        assert!(
            (coefficients[0] - (-0.625)).abs() < 1e-6,
            "{:?}",
            coefficients
        );
        assert!(
            (coefficients[1] - (-0.25)).abs() < 1e-6,
            "{:?}",
            coefficients
        );
    }

    #[test]
    fn bwexpander_applies_increasing_powers_of_the_chirp() {
        let mut coefficients = [1.0f32, 1.0, 1.0, 1.0];
        bwexpander(&mut coefficients, 0.5);
        assert_eq!(coefficients, [0.5, 0.25, 0.125, 0.0625]);
        // Empty input must not panic.
        bwexpander(&mut [], 0.9);
    }

    /// The whitening filter is the exact inverse of the synthesis recursion: feed it a signal
    /// generated by the same AR coefficients and everything past the first `order` samples is zero.
    #[test]
    fn lpc_analysis_filter_whitens_its_own_ar_process() {
        let coefficients = [0.6f32, -0.2, 0.1];
        let mut signal = [0.0f32; 32];
        signal[0] = 1.0;
        signal[1] = -0.5;
        signal[2] = 0.25;
        for index in 3..32 {
            signal[index] = signal[index - 1] * coefficients[0]
                + signal[index - 2] * coefficients[1]
                + signal[index - 3] * coefficients[2];
        }
        let mut residual = [1.0f32; 32];
        lpc_analysis_filter(&mut residual, &coefficients, &signal, 32);
        assert_eq!(
            &residual[..3],
            &[0.0, 0.0, 0.0],
            "first Order samples are zeroed"
        );
        for (index, &value) in residual.iter().enumerate().skip(3) {
            assert!(value.abs() < 1e-5, "sample {index} = {value}");
        }
    }

    #[test]
    fn insertion_sort_decreasing_orders_the_first_k_and_reports_positions() {
        let mut values = [1.0f32, 9.0, 3.0, 7.0, 5.0];
        let mut indices = [0usize; 3];
        insertion_sort_decreasing(&mut values, &mut indices, 3);
        assert_eq!(&values[..3], &[9.0, 7.0, 5.0]);
        assert_eq!(indices, [1, 3, 4]);
    }

    /// K == L is the fully sorted case; the index vector must be a permutation.
    #[test]
    fn insertion_sort_decreasing_full_length() {
        let mut values = [2.0f32, 8.0, 8.0, 1.0];
        let mut indices = [0usize; 4];
        insertion_sort_decreasing(&mut values, &mut indices, 4);
        assert_eq!(values, [8.0, 8.0, 2.0, 1.0]);
        let mut seen = indices;
        seen.sort_unstable();
        assert_eq!(seen, [0, 1, 2, 3]);
    }

    #[test]
    fn insertion_sort_increasing_i32_orders_the_first_k() {
        let mut values = [50i32, 10, 40, 20, 30];
        let mut indices = [0usize; 2];
        insertion_sort_increasing_i32(&mut values, &mut indices, 2);
        assert_eq!(&values[..2], &[10, 20]);
        assert_eq!(indices, [1, 3]);
    }

    #[test]
    fn log2_matches_the_definition_on_powers_of_two() {
        for exponent in 0..16 {
            let value = f64::from(1u32 << exponent);
            assert!(
                (log2(value) - exponent as f32).abs() < 1e-4,
                "2^{exponent}: {}",
                log2(value)
            );
        }
    }

    #[test]
    fn sigmoid_is_a_half_at_zero_and_saturates() {
        assert!((sigmoid(0.0) - 0.5).abs() < 1e-7);
        assert!(sigmoid(20.0) > 0.999);
        assert!(sigmoid(-20.0) < 0.001);
    }

    /// `lrintf` rounds halves to **even**, not away from zero. Both directions are pinned because
    /// getting it wrong shifts every Q16 LPC coefficient by one on a tie.
    #[test]
    fn float2int_rounds_ties_to_even() {
        assert_eq!(float2int(0.5), 0);
        assert_eq!(float2int(1.5), 2);
        assert_eq!(float2int(2.5), 2);
        assert_eq!(float2int(-0.5), 0);
        assert_eq!(float2int(-1.5), -2);
        assert_eq!(float2int(-2.5), -2);
        assert_eq!(float2int(3.4), 3);
        assert_eq!(float2int(-3.6), -4);
    }

    #[test]
    fn float_short_array_conversions_saturate() {
        let mut shorts = [0i16; 4];
        float2short_array(&mut shorts, &[40_000.0, -40_000.0, 1.5, -1.5]);
        assert_eq!(shorts, [32_767, -32_768, 2, -2]);
        let mut floats = [0.0f32; 3];
        short2float_array(&mut floats, &[1, -1, 32_767]);
        assert_eq!(floats, [1.0, -1.0, 32_767.0]);
    }

    proptest! {
        /// Both accumulators must agree with a straightforward `f64` sum to within the rounding
        /// slack of reordering ~256 terms.
        #[test]
        fn energy_agrees_with_a_naive_sum(values in prop::collection::vec(-1000.0f32..1000.0, 0..256)) {
            let naive: f64 = values.iter().map(|&v| f64::from(v) * f64::from(v)).sum();
            let computed = energy(&values);
            prop_assert!((computed - naive).abs() <= naive * 1e-12 + 1e-9);
        }

        /// Bandwidth expansion can only shrink a coefficient's magnitude for a chirp in (0, 1].
        #[test]
        fn bwexpander_never_grows_a_coefficient(
            values in prop::collection::vec(-4.0f32..4.0, 1..24),
            chirp in 0.01f32..=1.0,
        ) {
            let original = values.clone();
            let mut expanded = values;
            bwexpander(&mut expanded, chirp);
            for (index, (&before, &after)) in original.iter().zip(expanded.iter()).enumerate() {
                prop_assert!(
                    after.abs() <= before.abs() + 1e-6,
                    "coefficient {index}: |{after}| > |{before}|"
                );
            }
        }

        /// Schur fed a *real* autocorrelation sequence — the only thing its callers ever pass —
        /// must stay finite, keep every reflection coefficient inside the unit circle, and return a
        /// non-negative residual energy. The `+ R0 * 1e-3 + 1` noise floor is exactly what
        /// `silk_find_pitch_lags_FLP:88` adds before calling it, and it is what makes the
        /// positive-definiteness hold for a silent input too.
        ///
        /// Feeding an *arbitrary* vector instead would be testing a case that cannot occur: an
        /// indefinite "autocorrelation" makes the recursion diverge by construction, in the C as
        /// much as here.
        #[test]
        fn schur_on_a_real_autocorrelation_is_stable(
            signal in prop::collection::vec(-8000.0f32..8000.0, 64..=64),
        ) {
            let mut corr = [0.0f32; 9];
            autocorrelation(&mut corr, &signal);
            corr[0] += corr[0] * 1e-3 + 1.0;
            let mut reflection = [0.0f32; 8];
            let residual = schur(&mut reflection, &corr);
            prop_assert!(residual.is_finite() && residual >= 0.0, "residual {residual}");
            for value in reflection {
                prop_assert!(value.is_finite() && value.abs() < 1.0, "reflection {value}");
            }
        }
    }
}
