//! CELT-only conformance: decode pure-CELT (mono, 48 kHz) Opus streams with our [`CeltDecoder`] and
//! score them against libopus' own decode via `opus_compare` (RFC 6716 §6 tolerance metric).
//!
//! The RFC's official `testvectorNN` streams are full Opus (SILK + hybrid + CELT interleaved), so
//! they cannot validate the CELT layer alone until the SILK decoder lands. To validate CELT *now*,
//! `opus_demo -e restricted-lowdelay` (`OPUS_APPLICATION_RESTRICTED_LOWDELAY` forces
//! `MODE_CELT_ONLY`) generates CELT-only `.bit` streams plus libopus' reference decode `.dec` under
//! `reference/opus/celt_only/` (gitignored, generated by `reference/opus/gen_celt_only.sh` — see
//! CONTRIBUTING.md). Each stream is asserted twice:
//!
//! 1. **Exact** — every packet must end on the encoder's range-coder `final_range`. A desync of even
//!    one symbol fails here, naming the packet.
//! 2. **Perceptual** — the decoded PCM must pass `opus_compare` against libopus' own decode, which is
//!    what RFC 6716 §6 actually defines as conformance.
//!
//! Like the main conformance harness, it is a no-op (prints a skip notice) when the vectors or
//! `opus_compare` are absent, so it never breaks CI on a machine without them. It does *not* pass
//! vacuously: with vectors present, at least one stream must actually have been scored.

use std::path::{Path, PathBuf};

use siphon_rtp_codec::opus::celt::decoder::CeltDecoder;
use siphon_rtp_codec::opus::packet::{self, Mode};

/// Conformance output rate (RFC 6716 §6 / `run_vectors.sh` uses 48000).
const CONFORMANCE_RATE_HZ: u32 = 48_000;

/// One packet from a `.bit` file: `[u32 BE len][u32 BE final_range][payload]` (libopus `opus_demo`).
struct BitPacket {
    payload: Vec<u8>,
    /// The *encoder's* range-coder final value for this packet. A conformant decoder must end the
    /// packet on exactly this value — `opus_demo` itself treats a mismatch as a hard error.
    final_range: u32,
}

/// Parse the `opus_demo` `.bit` framing. Returns `Err` on a truncated/implausible header.
fn parse_bit_stream(bytes: &[u8]) -> Result<Vec<BitPacket>, String> {
    let mut packets = Vec::new();
    let mut offset = 0usize;
    while offset < bytes.len() {
        if offset + 8 > bytes.len() {
            return Err(format!("truncated packet header at offset {offset}"));
        }
        let len = u32::from_be_bytes([
            bytes[offset],
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
        ]) as usize;
        let final_range = u32::from_be_bytes([
            bytes[offset + 4],
            bytes[offset + 5],
            bytes[offset + 6],
            bytes[offset + 7],
        ]);
        offset += 8;
        if len > 1 << 20 {
            return Err(format!(
                "implausible packet length {len} at offset {offset}"
            ));
        }
        if offset + len > bytes.len() {
            return Err(format!("packet payload overruns file at offset {offset}"));
        }
        packets.push(BitPacket {
            payload: bytes[offset..offset + len].to_vec(),
            final_range,
        });
        offset += len;
    }
    Ok(packets)
}

/// The CELT-only vector directory (`reference/opus/celt_only`), if present.
fn vector_dir() -> Option<PathBuf> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../reference/opus/celt_only");
    dir.is_dir().then_some(dir)
}

/// Decode one CELT-only `.bit` stream to interleaved little-endian 16-bit mono PCM, statefully
/// across packets (the CELT decode ring + energy history persist). `Err(reason)` if a packet is not
/// a mono CELT-only frame our decoder handles.
fn decode_celt_only(packets: &[BitPacket]) -> Result<Vec<u8>, String> {
    let mut celt = CeltDecoder::new().map_err(|e| format!("CeltDecoder::new: {e:?}"))?;
    let mut pcm_bytes = Vec::new();
    let mut frame_pcm = vec![0i16; 5760]; // ≥ max Opus frame (120 ms @ 48 kHz)
    for (index, bp) in packets.iter().enumerate() {
        if bp.payload.is_empty() {
            continue; // DTX / empty packet
        }
        let parsed = packet::parse(&bp.payload).map_err(|e| format!("packet {index}: {e:?}"))?;
        if parsed.toc.mode() != Mode::Celt {
            return Err(format!(
                "packet {index}: not CELT-only (mode {:?})",
                parsed.toc.mode()
            ));
        }
        if parsed.toc.channels() != 1 {
            return Err(format!("packet {index}: not mono"));
        }
        // The CELT `end` band comes from the packet bandwidth, exactly as `opus_decode_native` sets
        // `CELT_SET_END_BAND` before handing the frame to CELT (`opus_decoder.c:498-523`). Decoding a
        // narrowband packet as fullband desynchronises the range decoder.
        celt.set_band_range(
            0,
            CeltDecoder::end_band_for_bandwidth(parsed.toc.bandwidth()),
        )
        .map_err(|e| format!("packet {index}: set_band_range: {e:?}"))?;
        let frame_size = parsed.toc.samples_per_frame(CONFORMANCE_RATE_HZ);
        for frame in parsed.frames() {
            if frame.is_empty() {
                continue;
            }
            let n = celt
                .decode(frame, &mut frame_pcm[..frame_size], frame_size)
                .map_err(|e| format!("packet {index}: decode: {e:?}"))?;
            for &sample in &frame_pcm[..n] {
                pcm_bytes.extend_from_slice(&sample.to_le_bytes());
            }
        }
        // Exact oracle: our range decoder must finish the packet on the encoder's final range.
        // `opus_compare` is a tolerance metric and can pass a subtly desynchronised decode; this
        // cannot. Checked per packet so a failure names the exact packet that diverged.
        if celt.final_range() != bp.final_range {
            return Err(format!(
                "packet {index}: range coder desync — final_range {:#010x}, expected {:#010x}",
                celt.final_range(),
                bp.final_range
            ));
        }
    }
    Ok(pcm_bytes)
}

/// Run `opus_compare` over decoded PCM vs the reference `.dec` (mono). `Ok(())` on a pass.
///
/// The locally built, test-only C reference. Its location is `$SIPHON_RTP_OPUS_COMPARE`, falling back
/// to `/tmp/opus_compare` — an override matters because each worktree has its own untracked
/// `reference/` tree, so the oracle is normally built once and shared.
fn run_opus_compare(reference_dec: &Path, decoded_pcm: &[u8]) -> Result<(), String> {
    let compare = std::env::var_os("SIPHON_RTP_OPUS_COMPARE")
        .map_or_else(|| PathBuf::from("/tmp/opus_compare"), PathBuf::from);
    if !compare.exists() {
        return Err(format!("{} not built", compare.display()));
    }
    let tmp = std::env::temp_dir().join(format!("celt_only_{}.sw", std::process::id()));
    std::fs::write(&tmp, decoded_pcm).map_err(|e| e.to_string())?;
    let status = std::process::Command::new(&compare)
        .arg("-r")
        .arg(CONFORMANCE_RATE_HZ.to_string())
        .arg(reference_dec)
        .arg(&tmp)
        .status()
        .map_err(|e| e.to_string())?;
    let _ = std::fs::remove_file(&tmp);
    if status.success() {
        Ok(())
    } else {
        Err(format!("opus_compare exited {status}"))
    }
}

#[test]
fn celt_only_streams_match_libopus() {
    let Some(dir) = vector_dir() else {
        eprintln!("celt-only conformance: vectors not present — skipping");
        return;
    };
    let mut bit_files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .map(|rd| {
            rd.filter_map(Result::ok)
                .map(|e| e.path())
                .filter(|p| p.extension().is_some_and(|x| x == "bit"))
                .collect()
        })
        .unwrap_or_default();
    bit_files.sort();
    if bit_files.is_empty() {
        eprintln!(
            "celt-only conformance: no .bit files in {} — skipping",
            dir.display()
        );
        return;
    }

    let mut passed = Vec::new();
    let mut skipped = Vec::new();
    let mut failed = Vec::new();
    for bit_path in &bit_files {
        let name = bit_path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let dec_path = bit_path.with_extension("dec");
        let Ok(bytes) = std::fs::read(bit_path) else {
            skipped.push((name, "unreadable .bit".to_string()));
            continue;
        };
        let packets = match parse_bit_stream(&bytes) {
            Ok(p) => p,
            Err(error) => {
                failed.push((name, error));
                continue;
            }
        };
        let pcm = match decode_celt_only(&packets) {
            Ok(pcm) => pcm,
            Err(reason) => {
                failed.push((name, format!("decode: {reason}")));
                continue;
            }
        };
        match run_opus_compare(&dec_path, &pcm) {
            Ok(()) => passed.push(name),
            Err(reason) if reason.contains("not built") => skipped.push((name, reason)),
            Err(reason) => failed.push((name, reason)),
        }
    }

    eprintln!(
        "celt-only conformance: {} passed, {} skipped, {} failed",
        passed.len(),
        skipped.len(),
        failed.len()
    );
    eprintln!("  passed:  {passed:?}");
    eprintln!("  skipped: {skipped:?}");
    eprintln!("  failed:  {failed:?}");
    assert!(
        failed.is_empty(),
        "celt-only: {} stream(s) failed: {failed:?}",
        failed.len()
    );
    // Vectors were present (we got here), so at least one stream must have actually been scored.
    // Without this the test passes vacuously when `opus_compare` is missing and everything skips.
    assert!(
        !passed.is_empty(),
        "celt-only: {} stream(s) present but none scored — is opus_compare built? skipped={skipped:?}",
        bit_files.len()
    );
}
