//! SILK concealment conformance: decode the SILK-only streams **under simulated packet loss** and
//! diff the result against libopus' own output, sample for sample.
//!
//! RFC 6716 §4.4's packet-loss concealment and comfort noise are the only SILK stages with no
//! entropy-coder footprint at all. Nothing they do reaches the range decoder, so neither the
//! per-frame `rng`/`tell` check in `silk_excitation_conformance` nor the loss-free end-to-end gate in
//! `silk_only_conformance` can see them: a concealer that returned silence would pass both. This
//! harness is what covers them, and it is an *exact* check, not a perceptual one.
//!
//! It replays `opus_demo`'s own decode-side loss driver (`opus_demo.c:965-1010`) so the two sides see
//! the same sequence of calls:
//!
//! ```text
//!   packet lost              -> remember it, decode nothing yet
//!   packet arrives after N   -> N concealed frames, then the packet itself, except that
//!      losses                   the *last* concealed frame is decoded from this packet's LBRR
//!                               data instead when the packet carries any (in-band FEC)
//! ```
//!
//! which is why both §4.4 paths and the [`LossFlag::DecodeLbrr`] path are exercised. The loss pattern
//! is fixed and generated by `reference/opus/gen_silk_plc.sh` (recipe in CONTRIBUTING.md): isolated
//! single losses every 7th packet, plus a burst of three every 53rd, with the first three packets
//! always intact. Single losses hit `silk_PLC_conceal`'s first-loss branch; bursts hit the
//! second-stage attenuation tables and the comfort-noise level tracking.
//!
//! Two structural notes on the replay:
//!
//! * **Concealment is chunked into 20 ms.** `opus_decode_frame` recurses on anything longer
//!   (`opus_decoder.c:313-323`), so a lost 40 ms packet is concealed as two independent 20 ms SILK
//!   calls, each with `newPacketFlag` set. Configuring for 40 ms and looping would give the same
//!   samples, but mirroring the chunking keeps the correspondence to the C obvious.
//! * **A packet decoded for FEC is then decoded again normally.** libopus runs the same bytes
//!   through the decoder twice — once as `FLAG_DECODE_LBRR` to fill the gap, once as
//!   `FLAG_DECODE_NORMAL` for its own interval — and the second decode sees the state the first left
//!   behind. That is reproduced, not shortcut.
//!
//! Skips gracefully when the `.plcdec` references are absent, and refuses to pass vacuously: it
//! counts concealed and FEC-recovered frames and fails if either is trivial.

use std::ops::Range;
use std::path::{Path, PathBuf};

use siphon_rtp_codec::opus::packet::{self, Mode};
use siphon_rtp_codec::opus::range_coder::RangeDecoder;
use siphon_rtp_codec::opus::silk::decoder::SilkDecoder;
use siphon_rtp_codec::opus::silk::frame::LossFlag;
use siphon_rtp_codec::opus::silk::types::InternalRate;

/// Conformance output rate — what `gen_silk_plc.sh` decoded the reference with.
const REFERENCE_RATE_HZ: u32 = 48_000;
/// Output channels. The reference `.plcdec` is always 2-channel.
const REFERENCE_CHANNELS: usize = 2;
/// `opus_decoder.c:454` — the spare-bit threshold above which libopus looks for a redundancy frame.
const REDUNDANCY_SPARE_BITS: i32 = 17;

/// The loss pattern `gen_silk_plc.sh` writes, reproduced exactly.
fn packet_is_lost(index: usize) -> bool {
    index >= 3 && (index % 7 == 3 || (index % 53 >= 17 && index % 53 <= 19))
}

/// Parse the `opus_demo` `.bit` framing: `[u32 BE len][u32 BE final_range][payload]`.
fn parse_bit_stream(bytes: &[u8]) -> Result<Vec<Vec<u8>>, String> {
    let mut packets = Vec::new();
    let mut offset = 0usize;
    while offset < bytes.len() {
        if offset + 8 > bytes.len() {
            return Err(format!("truncated packet header at offset {offset}"));
        }
        let length = u32::from_be_bytes([
            bytes[offset],
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
        ]) as usize;
        offset += 8;
        if offset + length > bytes.len() {
            return Err(format!("packet payload overruns file at offset {offset}"));
        }
        packets.push(bytes[offset..offset + length].to_vec());
        offset += length;
    }
    Ok(packets)
}

/// `opus_packet_has_lbrr` (`opus_decoder.c:1139-1162`) — does this packet carry in-band FEC?
///
/// The LBRR flag sits at a fixed bit position in the first payload byte, right after the per-frame
/// VAD flags, so it can be read without decoding anything.
fn packet_has_lbrr(
    payload: &[u8],
    frame: &[u8],
    samples_per_frame: usize,
    channels: usize,
) -> bool {
    if payload.is_empty() || frame.is_empty() {
        return false;
    }
    let frames_per_packet = if samples_per_frame > 960 {
        samples_per_frame / 960
    } else {
        1
    };
    let first = frame[0];
    let mut lbrr = (first >> (7 - frames_per_packet)) & 1 == 1;
    if channels == 2 {
        lbrr = lbrr || (first >> (6 - 2 * frames_per_packet)) & 1 == 1;
    }
    lbrr
}

/// The geometry one packet fixes: what the concealer for the *next* gap will be configured with.
#[derive(Debug, Clone, Copy)]
struct Geometry {
    channels: usize,
    rate: InternalRate,
    duration_ms: usize,
}

/// What the run exercised, so it cannot pass vacuously.
#[derive(Debug, Default)]
struct Coverage {
    concealed_frames: usize,
    fec_frames: usize,
    good_frames: usize,
    streams: usize,
    lbrr_packets: usize,
    redundancy_packets: usize,
}

impl Coverage {
    fn absorb(&mut self, other: &Coverage) {
        self.concealed_frames += other.concealed_frames;
        self.fec_frames += other.fec_frames;
        self.good_frames += other.good_frames;
        self.streams += other.streams;
        self.lbrr_packets += other.lbrr_packets;
        self.redundancy_packets += other.redundancy_packets;
    }
}

/// One decoded stream under loss: interleaved 48 kHz stereo PCM, the sample ranges the top-level
/// Opus decoder would have overwritten with a redundancy frame, and what the replay exercised.
struct Replayed {
    pcm: Vec<i16>,
    excluded: Vec<Range<usize>>,
    coverage: Coverage,
}

/// Replay `opus_demo`'s loss driver over one stream.
fn decode_with_loss(packets: &[Vec<u8>]) -> Result<Replayed, String> {
    let mut silk = SilkDecoder::new(REFERENCE_RATE_HZ, REFERENCE_CHANNELS)
        .map_err(|error| format!("SilkDecoder::new: {error:?}"))?;
    let mut coverage = Coverage::default();
    let mut pcm: Vec<i16> = Vec::new();
    let mut excluded: Vec<Range<usize>> = Vec::new();
    // 60 ms at 48 kHz, stereo.
    let mut frame_pcm = vec![0i16; 2880 * REFERENCE_CHANNELS];

    let mut lost_count = 0usize;
    // `st->stream_channels` / `internalSampleRate` / `last_packet_duration`: only a real packet
    // updates them, so concealment runs at whatever the last good packet established
    // (`opus_decoder.c:394-412`).
    let mut previous: Option<Geometry> = None;

    for (index, payload) in packets.iter().enumerate() {
        if packet_is_lost(index) || payload.is_empty() {
            lost_count += 1;
            continue;
        }
        let parsed =
            packet::parse(payload).map_err(|error| format!("packet {index}: {error:?}"))?;
        if parsed.toc.mode() != Mode::Silk {
            return Err(format!("packet {index}: not SILK-only"));
        }
        let frame = parsed.frames()[0];
        if frame.is_empty() {
            lost_count += 1;
            continue;
        }
        let geometry = Geometry {
            channels: usize::from(parsed.toc.channels()),
            rate: InternalRate::from_bandwidth(parsed.toc.bandwidth()),
            duration_ms: parsed.toc.samples_per_frame(REFERENCE_RATE_HZ)
                / (REFERENCE_RATE_HZ as usize / 1000),
        };
        let has_lbrr = packet_has_lbrr(
            payload,
            frame,
            parsed.toc.samples_per_frame(REFERENCE_RATE_HZ),
            geometry.channels,
        );
        if has_lbrr {
            coverage.lbrr_packets += 1;
        }

        for step in 0..=lost_count {
            if step < lost_count {
                let Some(gap) = previous else {
                    // libopus returns zeros until it has seen a packet (`opus_decoder.c:300-306`).
                    return Err(format!(
                        "packet {index}: loss before the first good packet is not covered by \
                         this pattern"
                    ));
                };
                // The last gap frame comes from this packet's LBRR data when it has any, and the
                // durations agree — otherwise `opus_decode_native` falls back to plain concealment.
                if step + 1 == lost_count && has_lbrr && gap.duration_ms == geometry.duration_ms {
                    silk.configure(geometry.channels, geometry.rate, geometry.duration_ms)
                        .map_err(|error| format!("packet {index}: configure: {error:?}"))?;
                    let mut range = RangeDecoder::new(frame);
                    let produced = silk
                        .decode(Some(&mut range), LossFlag::DecodeLbrr, &mut frame_pcm)
                        .map_err(|error| format!("packet {index}: fec decode: {error:?}"))?;
                    pcm.extend_from_slice(&frame_pcm[..produced * REFERENCE_CHANNELS]);
                    coverage.fec_frames += 1;
                    continue;
                }
                // Plain concealment, in 20 ms chunks (`opus_decoder.c:313-323`).
                let chunk_ms = gap.duration_ms.min(20);
                for _ in 0..(gap.duration_ms / chunk_ms) {
                    silk.configure(gap.channels, gap.rate, chunk_ms)
                        .map_err(|error| format!("packet {index}: configure: {error:?}"))?;
                    let produced = silk
                        .decode_silk_frame(None, LossFlag::PacketLost, true, &mut frame_pcm)
                        .map_err(|error| format!("packet {index}: conceal: {error:?}"))?;
                    pcm.extend_from_slice(&frame_pcm[..produced * REFERENCE_CHANNELS]);
                }
                coverage.concealed_frames += 1;
            } else {
                silk.configure(geometry.channels, geometry.rate, geometry.duration_ms)
                    .map_err(|error| format!("packet {index}: configure: {error:?}"))?;
                let start = pcm.len();
                let mut range = RangeDecoder::new(frame);
                let produced = silk
                    .decode(Some(&mut range), LossFlag::Normal, &mut frame_pcm)
                    .map_err(|error| format!("packet {index}: decode: {error:?}"))?;
                pcm.extend_from_slice(&frame_pcm[..produced * REFERENCE_CHANNELS]);
                // Same Opus-layer corner case `silk_only_conformance` documents: with 17 or more
                // spare bits libopus folds a CELT redundancy frame over the tail of this packet's
                // output (`opus_decoder.c:452-480`). It leaves the SILK state untouched, so the
                // concealment that follows is still comparable — only these samples are not.
                if range.tell() + REDUNDANCY_SPARE_BITS <= 8 * frame.len() as i32 {
                    excluded.push(start..pcm.len());
                }
                coverage.good_frames += 1;
            }
        }
        previous = Some(geometry);
        lost_count = 0;
    }
    coverage.streams = 1;
    Ok(Replayed {
        pcm,
        excluded,
        coverage,
    })
}

/// Drop every excluded range from `samples`, in interleaved-sample units.
fn without_excluded(samples: &[i16], excluded: &[Range<usize>]) -> Vec<i16> {
    if excluded.is_empty() {
        return samples.to_vec();
    }
    let mut kept = Vec::with_capacity(samples.len());
    let mut cursor = 0usize;
    for range in excluded {
        let end = range.start.min(samples.len());
        if cursor < end {
            kept.extend_from_slice(&samples[cursor..end]);
        }
        cursor = range.end.min(samples.len()).max(cursor);
    }
    if cursor < samples.len() {
        kept.extend_from_slice(&samples[cursor..]);
    }
    kept
}

/// `reference/opus/silk_only`, if present.
fn vector_dir() -> Option<PathBuf> {
    let directory = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../reference/opus/silk_only");
    directory.is_dir().then_some(directory)
}

fn score_stream(bit_path: &Path) -> Result<Option<Coverage>, String> {
    let reference_path = bit_path.with_extension("plcdec");
    if !reference_path.exists() {
        return Ok(None);
    }
    let bytes = std::fs::read(bit_path).map_err(|error| format!("unreadable .bit: {error}"))?;
    let packets = parse_bit_stream(&bytes)?;
    let Replayed {
        pcm,
        excluded,
        mut coverage,
    } = decode_with_loss(&packets)?;

    let reference_bytes =
        std::fs::read(&reference_path).map_err(|error| format!("unreadable .plcdec: {error}"))?;
    let reference: Vec<i16> = reference_bytes
        .chunks_exact(2)
        .map(|pair| i16::from_le_bytes([pair[0], pair[1]]))
        .collect();
    if reference.len() != pcm.len() {
        return Err(format!(
            "sample count {} != libopus {} — the loss replay drifted out of step",
            pcm.len(),
            reference.len()
        ));
    }
    coverage.redundancy_packets = excluded.len();
    let ours = without_excluded(&pcm, &excluded);
    let theirs = without_excluded(&reference, &excluded);
    if let Some((index, (&mine, &reference_sample))) = ours
        .iter()
        .zip(theirs.iter())
        .enumerate()
        .find(|(_, (a, b))| a != b)
    {
        let differing = ours
            .iter()
            .zip(theirs.iter())
            .filter(|(a, b)| a != b)
            .count();
        return Err(format!(
            "sample {index} is {mine}, libopus says {reference_sample} ({differing} of {} differ)",
            ours.len()
        ));
    }
    Ok(Some(coverage))
}

#[test]
fn silk_concealment_matches_libopus_under_loss() {
    let Some(directory) = vector_dir() else {
        eprintln!("silk concealment conformance: vectors not present — skipping");
        return;
    };
    let mut bit_files: Vec<PathBuf> = std::fs::read_dir(&directory)
        .map(|entries| {
            entries
                .filter_map(Result::ok)
                .map(|entry| entry.path())
                .filter(|path| path.extension().is_some_and(|extension| extension == "bit"))
                .collect()
        })
        .unwrap_or_default();
    bit_files.sort();
    if bit_files.is_empty() {
        eprintln!(
            "silk concealment conformance: no .bit files in {} — skipping",
            directory.display()
        );
        return;
    }

    let mut passed = Vec::new();
    let mut skipped = Vec::new();
    let mut failed = Vec::new();
    let mut total = Coverage::default();

    for bit_path in &bit_files {
        let name = bit_path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        match score_stream(bit_path) {
            Ok(Some(coverage)) => {
                total.absorb(&coverage);
                passed.push(name);
            }
            Ok(None) => skipped.push((name, "no .plcdec — run gen_silk_plc.sh".to_string())),
            Err(reason) => failed.push((name, reason)),
        }
    }

    eprintln!(
        "silk concealment conformance: {} passed, {} skipped, {} failed",
        passed.len(),
        skipped.len(),
        failed.len()
    );
    eprintln!(
        "  coverage: {} streams, {} good frames, {} concealed frames, {} FEC-recovered frames, \
         {} packets carrying LBRR; {} packet(s) excluded as carrying an Opus-layer redundancy frame",
        total.streams,
        total.good_frames,
        total.concealed_frames,
        total.fec_frames,
        total.lbrr_packets,
        total.redundancy_packets
    );
    if !failed.is_empty() {
        eprintln!("  failed: {failed:?}");
    }
    assert!(
        failed.is_empty(),
        "silk concealment: {} stream(s) failed: {failed:?}",
        failed.len()
    );
    if passed.is_empty() {
        eprintln!("silk concealment conformance: no .plcdec references — skipping");
        return;
    }
    // The pattern is meant to conceal a lot and to recover some of it from in-band FEC. If either
    // count collapses, the harness is measuring nothing.
    assert!(
        total.concealed_frames > 1_000,
        "only {} concealed frames — the loss pattern did not fire",
        total.concealed_frames
    );
    assert!(
        total.fec_frames > 100,
        "only {} FEC-recovered frames — the LBRR path was not exercised",
        total.fec_frames
    );
}
